export enum currentRole {
    engineer = 'Engineer',
    software_engineer = 'Software Engineer',
    mobile_developer = 'Mobile Developer',
    ios_developer = 'iOS Developer',
    android_developer = 'Android Developer',
    frontend_engineer = 'Frontend Engineer',
    backend_engineer = 'Backend Engineer',
    full_stack_engineer = 'Full-Stack Engineer',
    software_architect = 'Software Architect',
    embedded_engineer = 'Embedded Engineer',
    data_engineer = 'Data Engineer',
    security_engineer = 'Security Engineer',
    machine_learning_engineer = 'Machine Learning Engineer',
}
